version: 2
jobs:
  init:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run:
          name: Initial
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    docker: 
      - image: circleci/node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: yarn test

  publish:
    docker: 
      - image: circleci/node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build
          command: yarn build
      - run:
          name: Tag
          command: yarn release
      - run:
          name: Auth NPM
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ./.npmrc
      - run:
          name: Publish
          command: npm publish

workflows:
  version: 2
  default:
    jobs:
      - init
      - test:
          requires:
            - init
      - publish:
          requires:
            - test
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
            branches:
              only: master